### PR TITLE
Check protocol when opening connection without ignoreSsl

### LINKED ISSUE #666: download http source err with cast to https failure in Android
ERROR MSG :
W/System.err: java.lang.ClassCastException: com.android.okhttp.internal.huc.HttpURLConnectionImpl cannot be cast to javax.net.ssl.HttpsURLConnection
W/System.err:     at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.java:317)
W/System.err:     at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.java:235)

________

see the source code fo DownloadWorker,found that "        ignoreSsl = getInputData().getBoolean(ARG_IGNORESSL, false);"  ignoreSsl is always false

### PR DESCRIPTION
**Pull request by jmshrv**
Fixes #666

### CODE REVIEW

**Comment by bartekpacia** [comment]
Thanks. Have you verified it works?

**Comment by jmshrv** [comment]
I've verified it on a HTTP server, I'll test on a HTTPS server now.

**Comment by jmshrv** [comment]
Verified on HTTPS :)

**Comment by bartekpacia** [comment]
Thanks for your contribution!

Do you also think that the README should be updated? If yes it'd be great to have this done as well :)

**Comment by jmshrv** [comment]
That would be a good idea, I assumed that `ignoreSsl` was to allow bad HTTPS certs. I'll do this now

**Pull request merged**
