### PR TITLE
[WIP] Flutter Downloader 2.0

### PR DESCRIPTION
**Pull request by hnvn**
The changes of external storage APIs in Android 11 cause some problems with the current implementation. App can no longer create dedicated or app-specific directories with external storage so that `savedDir` is broken and becomes confused. 

This PR will focus on following tasks:
 - [ ] Re-design `enqueue()` API with new strategy to manage download location.
 - [ ] Support new `metadata` field in built-in SQLite database that helps developers store additional data for download tasks. (see #195)

### CODE REVIEW

**Comment by azeek** [comment]
#332  
Don't forget this.
Concurrent download limit does not work on ios.

**Comment by 838** [comment]
#500 and #260 🤘

**Comment by UnicornsOnLSD** [comment]
It'd also be awesome to see #283, although it looks like it hasn't been worked on in a while

**Comment by UnicornsOnLSD** [comment]
It would be useful to be able to pass platform-specific URLs since that's what iOS/Android seem to want, and it looks like file_picker can return the native URL for files (and I may make a PR to add returning URLs for directories).

**Comment by drahmedgabr** [comment]
Hello ..
My app path is emulated/0/Documents/MyApp
this is ok with Android 11 but plugin force download to Downloads folder
how to change this?

**Comment by ABDERRAHMANE-OUALI** [comment]
@drahmedgabr  You can use use **Dio** and **Path Provider**  as alternative, with **Dio** package you can download files from url fairly simply with one line of code, but you have to implement  the loader indicator your self

**Comment by drahmedgabr** [comment]
@ABDERRAHMANE-OUALI  Thanks bro .. you helped me so much .. جزاكم الله كل خير

**Comment by ABDERRAHMANE-OUALI** [comment]
@drahmedgabr np

**Comment by hnvn** [comment]
@Faaatman , I am quite busy now, not sure about time that I can work on this PR.

**Comment by bartekpacia** [comment]
Closing because not much work has been done here, but lots of good ideas. References it in #639 so these ideas are not lost :)

**Pull request closed without merging**
