### PR TITLE
Swift migration

### LINKED ISSUE #693: Siwft Conversion Discussion
I am in the process of converting the iOS plugin to Swift.

As part of this process there's a couple proposals I would like to make.

1) Move the database implementation to Dart. Potentially using Hive instead of sql.
So far this is significantly simplifying the codebase. One side-effect of this is removing the raw query method. Instead we could just provide the Hive box of download tasks.
At a later date the Android side could be converted to use the same Hive database. In the end there is less code to maintain.

2) Remove taskId from the Hive DownloadTask object model. Instead use id and rely on the platform's identifier.
Side effect of this is that I don't believe you can "update" the id of an existing object model. Instead the model must be deleted and a new model created. I'm not sure if this will cause problems. At the very least I can provide the new id.

### PR DESCRIPTION
**Pull request by Hackmodford**
- Converted Objective-C code to Swift
- Experimenting with using Hive instead of native SQLite db.

fixes #693

### CODE REVIEW

**Comment by bartekpacia** [comment]
Minor but cool (I guess) thing: please use [swift-format](https://formulae.brew.sh/formula/swift-format) so that the code formatting is consistent.

Once you install it, just do `swift-format format --recursive --in-place .` to format all files `.swift` files in all subdirectories.

**Comment by lyio** [comment]
@Hackmodford does Hive require migrations?

**Comment by Hackmodford** [comment]
I think it does. But found ISAR works better especially with Flutter Isolates.
https://pub.dev/packages/isar

**Comment by lyio** [comment]
Regarding the Hive part: I understood that the native SQLite database exists so the the plugin can manage its task irrespective of Flutter at all. The Hive DB ist not readily accessible from native code, is it?

**Comment by bartekpacia** [comment]
Closing in favor of #793. Thanks a lot for all the work anyway, it was useful :)

**Pull request closed without merging**
