### PR TITLE
Add SQLite migration from version 2 to 3

### PR DESCRIPTION
**Pull request by UnicornsOnLSD**
Currently, the database is just deleted when migrating. This can be pretty confusing when upgrading flutter_downloader, and may cause issues in apps that depend on the database always being there. This PR adds a simple migration from version 2 to 3 so that the database is upgraded instead of deleted.

### CODE REVIEW

**Comment by bartekpacia** [comment]
Thank you very much for your contribution @UnicornsOnLSD and sorry for my late response.

This looks nice. Could we do the same for iOS?

**Comment by UnicornsOnLSD** [comment]
I don't think a migration is required for iOS, as `saveInPublicStorage` is Android-only.

**Comment by bartekpacia** [comment]
Ah, right :)

Also, how can I define a new schema version? As in, if I update the schema and want to set its version to e.g `4`, where can I do it?

**Comment by UnicornsOnLSD** [comment]
On Android it's set here: https://github.com/fluttercommunity/flutter_downloader/blob/00a229950ab839c6d626e77a48175487bc1c313b/android/src/main/java/vn/hunghd/flutterdownloader/TaskDbHelper.java#L10

I'd assume there's a similar line somewhere for iOS, I haven't really touched the iOS code :)

**Comment by bartekpacia** [comment]
Great, thank you very much! :)

**Pull request merged**
