### PR TITLE
Update DBManager.m

### PR DESCRIPTION
**Pull request by FilipeMLFreitas**
download_tasks.db should be created in internal app directory (#722)

https://github.com/fluttercommunity/flutter_downloader/issues/722

### CODE REVIEW

**Comment by bartekpacia** [comment]
Sorry for the failing Action, it's my fault. Please use the newest `master`, it should be fixed.

**Comment by Hackmodford** [comment]
I think there's a decent argument for switching. The documents directory is defined as user accessible. However, could this potentially cause issues if an update is performed while a download is in progress?

We might want to consider migrating the db file to ensure backwards compatibility.

**Comment by lyio** [comment]
@Hackmodford I agree here. But there is no database migration for iOS at all. So it's not trivial to add this here.

We'd have to look for the DB file in the new location and in the old location and move it over if it exists in the old one.

**Comment by bartekpacia** [comment]
Looks like the migration part was done in #757 by @ndelanou :)

**Pull request merged**
