### PR TITLE
fix: remove networktype requirement

### PR DESCRIPTION
**Pull request by yuxizhe**
maybe fix: #129 

But I don't think its a good solution... 🤔

### CODE REVIEW

**Comment by hnvn** [comment]
Have you tried to discuss your matter in `WorkManager` repository yet? I think you can have a better solution from there.

**Comment by bartekpacia** [comment]
Yeah, try submitting a bug report at [Google Issue Tracker for WorkManager library](https://issuetracker.google.com/issues?q=workmanager). This is a problem at the platform level. I'm hesitant about implementing a workaround for this in the package itself.

**Comment by Albert221** [comment]
What if we made it available to the developer to change the `requiredNetworkType` with proper explanations referring the #129, so that this package could still be used, just on developer's own responsibility?

**Comment by bartekpacia** [comment]
@Albert221 That'd be another flag which is always present but has effect only on Android. As an escape hatch – okay, but we already have many such escape hatches. But I think you convinced me - there're many Flutter devs in China mainland who should be able to use this plugin without forking. I'm open to a PR.

That said, I'm thinking about creating per-platform classes (like the `flutter_local_notifications` package does). So we'd have `AndroidFlutterDownloaderPlugin` and `IOSFlutterDownloaderPlugin`, and they'd implement the platform-specific options.

**Pull request closed without merging**
