### PR TITLE
Log only when `debug` is true + clean up documentation

### PR DESCRIPTION
**Pull request by bartekpacia**
A bunch of smaller refactors

- formatted all code using `flutter format`
- added linting using [flutter_lints](https://pub.dev/packages/flutter_lints)
- added a GitHub Action which runs `flutter format` and `flutter analyze` for Pull Requests. This will require new code to conform to a single style

- if `FlutterDownloader.initialize(debug: false)` is called, then no logs will be printed to the console (at least on the Dart side).

I also rewrote most of the docs. I strived for conformance with [Effective Dart guide](https://dart.dev/guides/language/effective-dart/documentation).

@hnvn, please review if you have some free time :)

### CODE REVIEW

**Comment by hnvn** [comment]
LGTM

**Comment by bartekpacia** [comment]
@hnvn This adds [flutter_lints v2](https://pub.dev/packages/flutter_lints/changelog#200), which require Dart 2.17. This makes this package require Dart 2.17. Might be worth to add this info to README about new version.

**Comment by hnvn** [comment]
I think we should update new constraint version of Dart 2.17 in CHANGELOG

**Comment by hnvn** [comment]
BTW, GithubAction get failed, could you view the log of GithubAction?

**Comment by bartekpacia** [comment]
@hnvn yes, I've seen it. It's because of the Dart version.

**Pull request merged**
