### PR TITLE
Add option to download only on wifi

### PR DESCRIPTION
**Pull request by lyio**
+ Add `allowCellular` flag to Dart and default 
+ Add flag to Android code and pass it to the `WorkManager`
+ Migrate the database on Android

### CODE REVIEW

**Comment by bartekpacia** [comment]
Hi, thanks for contributing!

Could you also implement this on iOS? There are already many options that work only on Android.

**Comment by lyio** [comment]
@bartekpacia yes, I was planning on getting to that right away. Android was just easier and I wanted to open the PR as early as possible to get feedback and have the CI pipeline run.

**Comment by bartekpacia** [comment]
@lyio Sure, np :)

Regarding the failing CI run: please rebase with `master` – I made a small fix and now it should be all green.

**Comment by lyio** [comment]
@bartekpacia thank you for merging this. But please note that this is Android only at this point. I wanted to deliver the iOS implementation as well.

But I wanted to wait for the update of the DBManager in #728 or even the Swift migration in #709 .

**Comment by bartekpacia** [comment]
@lyio I've just merged #728, now you can proceed with implementation. Thanks a lot for your help! :)

Regarding the Swift migration – I think it's faster to rewrite existing Objective-C to Swift instead of having to invent this feature ("download only on wifi") from the start.

So no matter what we do, we will benefit from this feature :)

**Pull request merged**
