### PR TITLE
Hotfix: file is not saved on savedDir

### PR DESCRIPTION
**Pull request by huynguyennovem**
👉 This PR to help:
Hot fix the mistake from PR #522 

👉 Reference opened issue: 
#525 

👉 Demo:

https://user-images.githubusercontent.com/29337364/132745099-bb6cabf5-f5c3-42f5-82b5-a5ee40b1800a.mp4

### CODE REVIEW

**Comment by Jayshanx** [comment]
thanks! Hope to merge soon

**Comment by ali2236** [comment]
Pausing & Resuming Still doesn't work
```
W/System.err(14073): java.lang.NullPointerException
W/System.err(14073): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:227)
W/System.err(14073): 	at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.java:363)
W/System.err(14073): 	at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.java:211)
W/System.err(14073): 	at androidx.work.Worker$1.run(Worker.java:85)
```

**Comment by teamDrt2803** [comment]
This seems to work just fine. But had to disable **openFileFromNotification** else the task failed everytime.

**Comment by hnvn** [comment]
LGTM. Thanks for your PR

**Pull request merged**
